{ config, pkgs, lib, inputs, ... }:

{
  imports = [
    ./hardware-configuration.nix   # generated by `nixos-generate-config`
  ];

  # --- Boot -------------------------------------------------------------
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  # Late 2013-2015 11" Air is 32-bit EFI on some earlier revisions but
  # the last 11" units (2015) are 64-bit EFI - systemd-boot is fine.
  # If nixos-generate-config detects a 32-bit EFI, switch to GRUB with
  # boot.loader.grub.efiSupport = true; boot.loader.grub.device = "nodev";

  # --- Networking ---------------------------------------------------------
  networking.hostName = "bilbo";
  networking.networkmanager.enable = true;
  # Tailscale mesh VPN. After first rebuild, bring it up with `tailscale up`
  # (interactive auth in a browser). tailscaled coexists fine with NM.
  services.tailscale.enable = true;
  time.timeZone = "Africa/Johannesburg";
  i18n.defaultLocale = "en_ZA.UTF-8";
  services.openssh.enable = true;

  # A1465 (2013-2015 11" Air) ships a Broadcom BCM4360 card (BCM94360CS2,
  # PCI 14e4:43a0). The in-kernel drivers DON'T drive it: b43 finds the card
  # but rejects its 802.11ac PHY (probe -95), and brcmfmac has no PCIe binding
  # for 43a0 (only 43602 firmware ships). The only working driver is the
  # proprietary broadcom-sta (wl) - verified building + associating (sees 5GHz
  # APs) on kernel 6.18. It taints the kernel and is incompatible with some CPU
  # security mitigations; acceptable on this casual-use Air.
  hardware.enableRedistributableFirmware = true;
  boot.kernelModules = [ "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];
  # Keep the in-kernel Broadcom drivers from grabbing the card first.
  boot.blacklistedKernelModules = [ "b43" "bcma" "ssb" "brcmsmac" "brcmfmac" ];
  # broadcom-sta is flagged insecure in nixpkgs. Allow it by name (not the
  # version-pinned permittedInsecurePackages string, which would break on the
  # next kernel bump).
  nixpkgs.config.allowInsecurePredicate = pkg:
    builtins.elem (lib.getName pkg) [ "broadcom-sta" ];

  # --- Users ---------------------------------------------------------
  users.users.kmf = {
    isNormalUser = true;
    description = "kmf";
    extraGroups = [ "wheel" "networkmanager" "video" "audio" "input" ];
    shell = pkgs.fish;
  };
  programs.fish.enable = true;

  # --- 1Password ------------------------------------------------------
  # Use the NixOS modules (not a bare package): they install the setuid
  # 1Password-BrowserSupport helper and polkit rules needed for browser
  # integration and system/biometric unlock. Unfree but Hydra-cached, so no
  # source build. `op` is the CLI; the GUI is Electron (heavy-ish on 4 GB).
  programs._1password.enable = true;              # `op` CLI
  programs._1password-gui = {
    enable = true;
    polkitPolicyOwners = [ "kmf" ];               # who may use system auth
  };

  # --- Nix settings ---------------------------------------------------
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  nixpkgs.config.allowUnfree = true;

  # --- Niri (Wayland compositor) --------------------------------------
  programs.niri.enable = true;
  # Use nixpkgs' prebuilt niri (cached on cache.nixos.org) instead of letting
  # niri-flake compile its own from source: niri-flake's Cachix only covers
  # nixos-unstable/25.05, so against nixpkgs 26.05 the source build is uncached
  # and OOM-kills rustc on this 4GB Air.
  programs.niri.package = pkgs.niri;

  # Login manager - DankMaterialShell's own graphical greeter (dms-greeter),
  # rendered inside niri via Quickshell. Provided by dms.nixosModules.greeter
  # (imported in flake.nix). The module sets greetd's default_session.command
  # itself, so we only enable greetd and point it at the greeter user.
  services.greetd.enable = true;
  services.greetd.settings.default_session.user = "greeter";
  programs.dank-material-shell.greeter = {
    enable = true;
    compositor.name = "niri";   # niri is enabled at system level above
    configHome = "/home/kmf";   # reuse kmf's DMS wallpaper/theme/settings.json
  };

  # DMS ships its own polkit agent; disable niri-flake's default one so
  # they don't both spawn and fight over prompts.
  systemd.user.services.niri-flake-polkit.enable = false;

  # --- Audio -----------------------------------------------------------
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    pulse.enable = true;
  };

  # --- MacBook-specific niceties ---------------------------------------
  # Fan control - the 11" Air runs hot under any sustained load.
  services.mbpfan.enable = true;

  powerManagement.enable = true;
  services.tlp.enable = true;   # battery life tuning, disable if it fights mbpfan

  # Screen backlight control
  hardware.acpilight.enable = true;

  # Keyboard backlight (applesmc LED smc::kbd_backlight). brightnessctl's udev
  # rules chgrp the leds/backlight sysfs nodes so a non-root user can write
  # them; the kbd_backlight LED node is granted to the `input` group (see kmf's
  # extraGroups). F5/F6 (KEY_KBDILLUM{DOWN,UP}) are bound in home.nix.
  services.udev.packages = [ pkgs.brightnessctl ];

  # Touchpad
  services.libinput.enable = true;

  # --- Flatpak ----------------------------------------------------------
  # xdg-desktop-portal is already provided (gnome backend, via niri-flake/DMS)
  # and xdg-document-portal is running, so Flatpak apps get file access and
  # portals out of the box - just enable the service. Add the flathub remote
  # once at runtime: flatpak remote-add --if-not-exists flathub \
  #   https://dl.flathub.org/repo/flathub.flatpakrepo
  services.flatpak.enable = true;

  system.stateVersion = "26.05";
}
