{ config, pkgs, lib, inputs, ... }:

{
  imports = [
    ./hardware-configuration.nix   # generated by `nixos-generate-config`
  ];

  # --- Boot -------------------------------------------------------------
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  # Late 2013-2015 11" Air is 32-bit EFI on some earlier revisions but
  # the last 11" units (2015) are 64-bit EFI - systemd-boot is fine.
  # If nixos-generate-config detects a 32-bit EFI, switch to GRUB with
  # boot.loader.grub.efiSupport = true; boot.loader.grub.device = "nodev";

  # --- Networking ---------------------------------------------------------
  networking.hostName = "bilbo";
  networking.networkmanager.enable = true;
  time.timeZone = "Africa/Johannesburg";
  i18n.defaultLocale = "en_ZA.UTF-8";
  services.openssh.enable = true;

  # A1465 (2013-2015 11" Air) ships a Broadcom BCM4360 card (module
  # BCM94360CS2), which the in-kernel brcmfmac driver handles fine on
  # recent kernels - just needs the firmware blob.
  hardware.enableRedistributableFirmware = true;
  # If wifi still doesn't show up after first boot, fall back to the
  # proprietary driver instead:
  #   boot.blacklistedKernelModules = [ "brcmfmac" ];
  #   boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];
  #   boot.kernelModules = [ "wl" ];

  # --- Users ---------------------------------------------------------
  users.users.kmf = {
    isNormalUser = true;
    description = "kmf";
    extraGroups = [ "wheel" "networkmanager" "video" "audio" ];
    shell = pkgs.fish;
  };
  programs.fish.enable = true;

  # --- Nix settings ---------------------------------------------------
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  nixpkgs.config.allowUnfree = true;

  # --- Niri (Wayland compositor) --------------------------------------
  programs.niri.enable = true;
  # Use nixpkgs' prebuilt niri (cached on cache.nixos.org) instead of letting
  # niri-flake compile its own from source: niri-flake's Cachix only covers
  # nixos-unstable/25.05, so against nixpkgs 26.05 the source build is uncached
  # and OOM-kills rustc on this 4GB Air.
  programs.niri.package = pkgs.niri;

  # Login manager - DankMaterialShell's own graphical greeter (dms-greeter),
  # rendered inside niri via Quickshell. Provided by dms.nixosModules.greeter
  # (imported in flake.nix). The module sets greetd's default_session.command
  # itself, so we only enable greetd and point it at the greeter user.
  services.greetd.enable = true;
  services.greetd.settings.default_session.user = "greeter";
  programs.dank-material-shell.greeter = {
    enable = true;
    compositor.name = "niri";   # niri is enabled at system level above
    configHome = "/home/kmf";   # reuse kmf's DMS wallpaper/theme/settings.json
  };

  # DMS ships its own polkit agent; disable niri-flake's default one so
  # they don't both spawn and fight over prompts.
  systemd.user.services.niri-flake-polkit.enable = false;

  # --- Audio -----------------------------------------------------------
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    pulse.enable = true;
  };

  # --- MacBook-specific niceties ---------------------------------------
  # Fan control - the 11" Air runs hot under any sustained load.
  services.mbpfan.enable = true;

  powerManagement.enable = true;
  services.tlp.enable = true;   # battery life tuning, disable if it fights mbpfan

  # Backlight control
  hardware.acpilight.enable = true;

  # Touchpad
  services.libinput.enable = true;

  # --- Flatpak ----------------------------------------------------------
  # xdg-desktop-portal is already provided (gnome backend, via niri-flake/DMS)
  # and xdg-document-portal is running, so Flatpak apps get file access and
  # portals out of the box - just enable the service. Add the flathub remote
  # once at runtime: flatpak remote-add --if-not-exists flathub \
  #   https://dl.flathub.org/repo/flathub.flatpakrepo
  services.flatpak.enable = true;

  system.stateVersion = "26.05";
}
